(function () {
  "use strict";

const rows = [
  // Afrika
  ["dz", "Algerie", "Alger", ["africa"]],
  ["ao", "Angola", "Luanda", ["africa"]],
  ["bj", "Benin", "Porto-Novo", ["africa"]],
  ["bw", "Botswana", "Gaborone", ["africa"]],
  ["bf", "Burkina Faso", "Ouagadougou", ["africa"]],
  ["bi", "Burundi", "Gitega", ["africa"]],
  ["cv", "Kapp Verde", "Praia", ["africa"]],
  ["cm", "Kamerun", "Yaoundé", ["africa"]],
  ["cf", "Den sentralafrikanske republikk", "Bangui", ["africa"]],
  ["td", "Tsjad", "N'Djamena", ["africa"]],
  ["km", "Komorene", "Moroni", ["africa"]],
  ["cg", "Republikken Kongo", "Brazzaville", ["africa"]],
  ["cd", "Den demokratiske republikken Kongo", "Kinshasa", ["africa"]],
  ["ci", "Elfenbenskysten", "Yamoussoukro", ["africa"]],
  ["dj", "Djibouti", "Djibouti", ["africa"]],
  ["eg", "Egypt", "Kairo", ["africa"]],
  ["gq", "Ekvatorial-Guinea", "Malabo", ["africa"]],
  ["er", "Eritrea", "Asmara", ["africa"]],
  ["sz", "Eswatini", "Mbabane / Lobamba", ["africa"]],
  ["et", "Etiopia", "Addis Abeba", ["africa"]],
  ["ga", "Gabon", "Libreville", ["africa"]],
  ["gm", "Gambia", "Banjul", ["africa"]],
  ["gh", "Ghana", "Accra", ["africa"]],
  ["gn", "Guinea", "Conakry", ["africa"]],
  ["gw", "Guinea-Bissau", "Bissau", ["africa"]],
  ["ke", "Kenya", "Nairobi", ["africa"]],
  ["ls", "Lesotho", "Maseru", ["africa"]],
  ["lr", "Liberia", "Monrovia", ["africa"]],
  ["ly", "Libya", "Tripoli", ["africa"]],
  ["mg", "Madagaskar", "Antananarivo", ["africa"]],
  ["mw", "Malawi", "Lilongwe", ["africa"]],
  ["ml", "Mali", "Bamako", ["africa"]],
  ["mr", "Mauritania", "Nouakchott", ["africa"]],
  ["mu", "Mauritius", "Port Louis", ["africa"]],
  ["ma", "Marokko", "Rabat", ["africa"]],
  ["mz", "Mosambik", "Maputo", ["africa"]],
  ["na", "Namibia", "Windhoek", ["africa"]],
  ["ne", "Niger", "Niamey", ["africa"]],
  ["ng", "Nigeria", "Abuja", ["africa"]],
  ["rw", "Rwanda", "Kigali", ["africa"]],
  ["st", "São Tomé og Príncipe", "São Tomé", ["africa"]],
  ["sn", "Senegal", "Dakar", ["africa"]],
  ["sc", "Seychellene", "Victoria", ["africa"]],
  ["sl", "Sierra Leone", "Freetown", ["africa"]],
  ["so", "Somalia", "Mogadishu", ["africa"]],
  ["za", "Sør-Afrika", "Pretoria / Cape Town / Bloemfontein", ["africa"]],
  ["ss", "Sør-Sudan", "Juba", ["africa"]],
  ["sd", "Sudan", "Khartoum", ["africa"]],
  ["tz", "Tanzania", "Dodoma", ["africa"]],
  ["tg", "Togo", "Lomé", ["africa"]],
  ["tn", "Tunisia", "Tunis", ["africa"]],
  ["ug", "Uganda", "Kampala", ["africa"]],
  ["zm", "Zambia", "Lusaka", ["africa"]],
  ["zw", "Zimbabwe", "Harare", ["africa"]],

  // Amerika
  ["ca", "Canada", "Ottawa", ["americas", "north-central-america"]],
  ["us", "USA", "Washington, D.C.", ["americas", "north-central-america"]],
  ["mx", "Mexico", "Mexico by", ["americas", "north-central-america"]],
  ["bz", "Belize", "Belmopan", ["americas", "north-central-america"]],
  ["cr", "Costa Rica", "San José", ["americas", "north-central-america"]],
  ["sv", "El Salvador", "San Salvador", ["americas", "north-central-america"]],
  ["gt", "Guatemala", "Guatemala by", ["americas", "north-central-america"]],
  ["hn", "Honduras", "Tegucigalpa", ["americas", "north-central-america"]],
  ["ni", "Nicaragua", "Managua", ["americas", "north-central-america"]],
  ["pa", "Panama", "Panama by", ["americas", "north-central-america"]],
  ["ag", "Antigua og Barbuda", "Saint John's", ["americas", "caribbean"]],
  ["bs", "Bahamas", "Nassau", ["americas", "caribbean"]],
  ["bb", "Barbados", "Bridgetown", ["americas", "caribbean"]],
  ["cu", "Cuba", "Havanna", ["americas", "caribbean"]],
  ["dm", "Dominica", "Roseau", ["americas", "caribbean"]],
  ["do", "Den dominikanske republikk", "Santo Domingo", ["americas", "caribbean"]],
  ["gd", "Grenada", "Saint George's", ["americas", "caribbean"]],
  ["ht", "Haiti", "Port-au-Prince", ["americas", "caribbean"]],
  ["jm", "Jamaica", "Kingston", ["americas", "caribbean"]],
  ["kn", "Saint Kitts og Nevis", "Basseterre", ["americas", "caribbean"]],
  ["lc", "Saint Lucia", "Castries", ["americas", "caribbean"]],
  ["vc", "Saint Vincent og Grenadinene", "Kingstown", ["americas", "caribbean"]],
  ["tt", "Trinidad og Tobago", "Port of Spain", ["americas", "caribbean"]],
  ["ar", "Argentina", "Buenos Aires", ["americas", "south-america"]],
  ["bo", "Bolivia", "Sucre / La Paz", ["americas", "south-america"]],
  ["br", "Brasil", "Brasília", ["americas", "south-america"]],
  ["cl", "Chile", "Santiago", ["americas", "south-america"]],
  ["co", "Colombia", "Bogotá", ["americas", "south-america"]],
  ["ec", "Ecuador", "Quito", ["americas", "south-america"]],
  ["gy", "Guyana", "Georgetown", ["americas", "south-america"]],
  ["py", "Paraguay", "Asunción", ["americas", "south-america"]],
  ["pe", "Peru", "Lima", ["americas", "south-america"]],
  ["sr", "Surinam", "Paramaribo", ["americas", "south-america"]],
  ["uy", "Uruguay", "Montevideo", ["americas", "south-america"]],
  ["ve", "Venezuela", "Caracas", ["americas", "south-america"]],

  // Asia
  ["af", "Afghanistan", "Kabul", ["asia"]],
  ["am", "Armenia", "Jerevan", ["asia"]],
  ["az", "Aserbajdsjan", "Baku", ["asia"]],
  ["bh", "Bahrain", "Manama", ["asia"]],
  ["bd", "Bangladesh", "Dhaka", ["asia"]],
  ["bt", "Bhutan", "Thimphu", ["asia"]],
  ["bn", "Brunei", "Bandar Seri Begawan", ["asia"]],
  ["kh", "Kambodsja", "Phnom Penh", ["asia"]],
  ["cn", "Kina", "Beijing", ["asia"]],
  ["cy", "Kypros", "Nikosia", ["asia", "europe"]],
  ["ge", "Georgia", "Tbilisi", ["asia"]],
  ["in", "India", "New Delhi", ["asia"]],
  ["id", "Indonesia", "Jakarta / Nusantara", ["asia"]],
  ["ir", "Iran", "Teheran", ["asia"]],
  ["iq", "Irak", "Bagdad", ["asia"]],
  ["il", "Israel", "Jerusalem", ["asia"]],
  ["jp", "Japan", "Tokyo", ["asia"]],
  ["jo", "Jordan", "Amman", ["asia"]],
  ["kz", "Kasakhstan", "Astana", ["asia"]],
  ["kw", "Kuwait", "Kuwait by", ["asia"]],
  ["kg", "Kirgisistan", "Bisjkek", ["asia"]],
  ["la", "Laos", "Vientiane", ["asia"]],
  ["lb", "Libanon", "Beirut", ["asia"]],
  ["my", "Malaysia", "Kuala Lumpur / Putrajaya", ["asia"]],
  ["mv", "Maldivene", "Malé", ["asia"]],
  ["mn", "Mongolia", "Ulaanbaatar", ["asia"]],
  ["mm", "Myanmar", "Naypyidaw", ["asia"]],
  ["np", "Nepal", "Katmandu", ["asia"]],
  ["kp", "Nord-Korea", "Pyongyang", ["asia"]],
  ["om", "Oman", "Muskat", ["asia"]],
  ["pk", "Pakistan", "Islamabad", ["asia"]],
  ["ps", "Palestina", "Øst-Jerusalem / Ramallah", ["asia"]],
  ["ph", "Filippinene", "Manila", ["asia"]],
  ["qa", "Qatar", "Doha", ["asia"]],
  ["sa", "Saudi-Arabia", "Riyadh", ["asia"]],
  ["sg", "Singapore", "Singapore", ["asia"]],
  ["kr", "Sør-Korea", "Seoul", ["asia"]],
  ["lk", "Sri Lanka", "Sri Jayawardenepura Kotte / Colombo", ["asia"]],
  ["sy", "Syria", "Damaskus", ["asia"]],
  ["tj", "Tadsjikistan", "Dusjanbe", ["asia"]],
  ["th", "Thailand", "Bangkok", ["asia"]],
  ["tl", "Øst-Timor", "Dili", ["asia"]],
  ["tr", "Tyrkia", "Ankara", ["asia", "europe"]],
  ["tm", "Turkmenistan", "Asjkhabad", ["asia"]],
  ["ae", "De forente arabiske emirater", "Abu Dhabi", ["asia"]],
  ["uz", "Usbekistan", "Tasjkent", ["asia"]],
  ["vn", "Vietnam", "Hanoi", ["asia"]],
  ["ye", "Jemen", "Sana", ["asia"]],

  // Europa
  ["al", "Albania", "Tirana", ["europe"]],
  ["ad", "Andorra", "Andorra la Vella", ["europe"]],
  ["at", "Østerrike", "Wien", ["europe"]],
  ["by", "Belarus", "Minsk", ["europe"]],
  ["be", "Belgia", "Brussel", ["europe"]],
  ["ba", "Bosnia-Hercegovina", "Sarajevo", ["europe"]],
  ["bg", "Bulgaria", "Sofia", ["europe"]],
  ["hr", "Kroatia", "Zagreb", ["europe"]],
  ["cz", "Tsjekkia", "Praha", ["europe"]],
  ["dk", "Danmark", "København", ["europe"]],
  ["ee", "Estland", "Tallinn", ["europe"]],
  ["fi", "Finland", "Helsinki", ["europe"]],
  ["fr", "Frankrike", "Paris", ["europe"]],
  ["de", "Tyskland", "Berlin", ["europe"]],
  ["gr", "Hellas", "Athen", ["europe"]],
  ["hu", "Ungarn", "Budapest", ["europe"]],
  ["is", "Island", "Reykjavík", ["europe"]],
  ["ie", "Irland", "Dublin", ["europe"]],
  ["it", "Italia", "Roma", ["europe"]],
  ["xk", "Kosovo", "Pristina", ["europe"]],
  ["lv", "Latvia", "Riga", ["europe"]],
  ["li", "Liechtenstein", "Vaduz", ["europe"]],
  ["lt", "Litauen", "Vilnius", ["europe"]],
  ["lu", "Luxembourg", "Luxembourg", ["europe"]],
  ["mt", "Malta", "Valletta", ["europe"]],
  ["md", "Moldova", "Chișinău", ["europe"]],
  ["mc", "Monaco", "Monaco", ["europe"]],
  ["me", "Montenegro", "Podgorica", ["europe"]],
  ["nl", "Nederland", "Amsterdam", ["europe"]],
  ["mk", "Nord-Makedonia", "Skopje", ["europe"]],
  ["no", "Norge", "Oslo", ["europe"]],
  ["pl", "Polen", "Warszawa", ["europe"]],
  ["pt", "Portugal", "Lisboa", ["europe"]],
  ["ro", "Romania", "București", ["europe"]],
  ["ru", "Russland", "Moskva", ["europe", "asia"]],
  ["sm", "San Marino", "San Marino", ["europe"]],
  ["rs", "Serbia", "Beograd", ["europe"]],
  ["sk", "Slovakia", "Bratislava", ["europe"]],
  ["si", "Slovenia", "Ljubljana", ["europe"]],
  ["es", "Spania", "Madrid", ["europe"]],
  ["se", "Sverige", "Stockholm", ["europe"]],
  ["ch", "Sveits", "Bern", ["europe"]],
  ["ua", "Ukraina", "Kyiv", ["europe"]],
  ["gb", "Storbritannia", "London", ["europe"]],
  ["va", "Vatikanstaten", "Vatikanstaten", ["europe"]],

  // Oseania
  ["au", "Australia", "Canberra", ["oceania"]],
  ["fj", "Fiji", "Suva", ["oceania"]],
  ["ki", "Kiribati", "South Tarawa", ["oceania"]],
  ["mh", "Marshalløyene", "Majuro", ["oceania"]],
  ["fm", "Mikronesiaføderasjonen", "Palikir", ["oceania"]],
  ["nr", "Nauru", "Yaren", ["oceania"]],
  ["nz", "New Zealand", "Wellington", ["oceania"]],
  ["pw", "Palau", "Ngerulmud", ["oceania"]],
  ["pg", "Papua Ny-Guinea", "Port Moresby", ["oceania"]],
  ["ws", "Samoa", "Apia", ["oceania"]],
  ["sb", "Salomonøyene", "Honiara", ["oceania"]],
  ["to", "Tonga", "Nukuʻalofa", ["oceania"]],
  ["tv", "Tuvalu", "Funafuti", ["oceania"]],
  ["vu", "Vanuatu", "Port Vila", ["oceania"]],
];

const countries = rows.map(([code, name, capital, regions]) => ({
  code,
  name,
  capital,
  regions,
}));

const regionOptions = [
  { id: "world", label: "Hele verden", eyebrow: "196 land" },
  { id: "europe", label: "Europa", eyebrow: "47 land" },
  { id: "africa", label: "Afrika", eyebrow: "54 land" },
  { id: "asia", label: "Asia", eyebrow: "49 land" },
  { id: "oceania", label: "Oseania", eyebrow: "14 land" },
  { id: "americas", label: "Amerika", eyebrow: "35 land" },
  {
    id: "north-central-america",
    label: "Nord- og Mellom-Amerika",
    eyebrow: "10 land",
  },
  { id: "south-america", label: "Sør-Amerika", eyebrow: "12 land" },
  { id: "caribbean", label: "Karibia", eyebrow: "13 land" },
];

window.ATLAS_DATA = Object.freeze({
  countries: Object.freeze(countries),
  regionOptions: Object.freeze(regionOptions),
});
})();
