(function () {
  "use strict";

const rows = [
  // Afrika
  ["dz", "Algerie", "Alger", "africa"],
  ["ao", "Angola", "Luanda", "africa"],
  ["bj", "Benin", "Porto-Novo", "africa"],
  ["bw", "Botswana", "Gaborone", "africa"],
  ["bf", "Burkina Faso", "Ouagadougou", "africa"],
  ["bi", "Burundi", "Gitega", "africa"],
  ["cv", "Kapp Verde", "Praia", "africa"],
  ["cm", "Kamerun", "Yaoundé", "africa"],
  ["cf", "Den sentralafrikanske republikk", "Bangui", "africa"],
  ["td", "Tsjad", "N'Djamena", "africa"],
  ["km", "Komorene", "Moroni", "africa"],
  ["cg", "Republikken Kongo", "Brazzaville", "africa"],
  ["cd", "Den demokratiske republikken Kongo", "Kinshasa", "africa"],
  ["ci", "Elfenbenskysten", "Yamoussoukro", "africa"],
  ["dj", "Djibouti", "Djibouti", "africa"],
  ["eg", "Egypt", "Kairo", "africa"],
  ["gq", "Ekvatorial-Guinea", "Malabo", "africa"],
  ["er", "Eritrea", "Asmara", "africa"],
  ["sz", "Eswatini", "Mbabane / Lobamba", "africa"],
  ["et", "Etiopia", "Addis Abeba", "africa"],
  ["ga", "Gabon", "Libreville", "africa"],
  ["gm", "Gambia", "Banjul", "africa"],
  ["gh", "Ghana", "Accra", "africa"],
  ["gn", "Guinea", "Conakry", "africa"],
  ["gw", "Guinea-Bissau", "Bissau", "africa"],
  ["ke", "Kenya", "Nairobi", "africa"],
  ["ls", "Lesotho", "Maseru", "africa"],
  ["lr", "Liberia", "Monrovia", "africa"],
  ["ly", "Libya", "Tripoli", "africa"],
  ["mg", "Madagaskar", "Antananarivo", "africa"],
  ["mw", "Malawi", "Lilongwe", "africa"],
  ["ml", "Mali", "Bamako", "africa"],
  ["mr", "Mauritania", "Nouakchott", "africa"],
  ["mu", "Mauritius", "Port Louis", "africa"],
  ["ma", "Marokko", "Rabat", "africa"],
  ["mz", "Mosambik", "Maputo", "africa"],
  ["na", "Namibia", "Windhoek", "africa"],
  ["ne", "Niger", "Niamey", "africa"],
  ["ng", "Nigeria", "Abuja", "africa"],
  ["rw", "Rwanda", "Kigali", "africa"],
  ["st", "São Tomé og Príncipe", "São Tomé", "africa"],
  ["sn", "Senegal", "Dakar", "africa"],
  ["sc", "Seychellene", "Victoria", "africa"],
  ["sl", "Sierra Leone", "Freetown", "africa"],
  ["so", "Somalia", "Mogadishu", "africa"],
  ["za", "Sør-Afrika", "Pretoria / Cape Town / Bloemfontein", "africa"],
  ["ss", "Sør-Sudan", "Juba", "africa"],
  ["sd", "Sudan", "Khartoum", "africa"],
  ["tz", "Tanzania", "Dodoma", "africa"],
  ["tg", "Togo", "Lomé", "africa"],
  ["tn", "Tunisia", "Tunis", "africa"],
  ["ug", "Uganda", "Kampala", "africa"],
  ["zm", "Zambia", "Lusaka", "africa"],
  ["zw", "Zimbabwe", "Harare", "africa"],

  // Amerika
  ["ca", "Canada", "Ottawa", "north-central-america"],
  ["us", "USA", "Washington, D.C.", "north-central-america"],
  ["mx", "Mexico", "Mexico by", "north-central-america"],
  ["bz", "Belize", "Belmopan", "north-central-america"],
  ["cr", "Costa Rica", "San José", "north-central-america"],
  ["sv", "El Salvador", "San Salvador", "north-central-america"],
  ["gt", "Guatemala", "Guatemala by", "north-central-america"],
  ["hn", "Honduras", "Tegucigalpa", "north-central-america"],
  ["ni", "Nicaragua", "Managua", "north-central-america"],
  ["pa", "Panama", "Panama by", "north-central-america"],
  ["ag", "Antigua og Barbuda", "Saint John's", "caribbean"],
  ["bs", "Bahamas", "Nassau", "caribbean"],
  ["bb", "Barbados", "Bridgetown", "caribbean"],
  ["cu", "Cuba", "Havanna", "caribbean"],
  ["dm", "Dominica", "Roseau", "caribbean"],
  ["do", "Den dominikanske republikk", "Santo Domingo", "caribbean"],
  ["gd", "Grenada", "Saint George's", "caribbean"],
  ["ht", "Haiti", "Port-au-Prince", "caribbean"],
  ["jm", "Jamaica", "Kingston", "caribbean"],
  ["kn", "Saint Kitts og Nevis", "Basseterre", "caribbean"],
  ["lc", "Saint Lucia", "Castries", "caribbean"],
  ["vc", "Saint Vincent og Grenadinene", "Kingstown", "caribbean"],
  ["tt", "Trinidad og Tobago", "Port of Spain", "caribbean"],
  ["ar", "Argentina", "Buenos Aires", "south-america"],
  ["bo", "Bolivia", "Sucre / La Paz", "south-america"],
  ["br", "Brasil", "Brasília", "south-america"],
  ["cl", "Chile", "Santiago", "south-america"],
  ["co", "Colombia", "Bogotá", "south-america"],
  ["ec", "Ecuador", "Quito", "south-america"],
  ["gy", "Guyana", "Georgetown", "south-america"],
  ["py", "Paraguay", "Asunción", "south-america"],
  ["pe", "Peru", "Lima", "south-america"],
  ["sr", "Surinam", "Paramaribo", "south-america"],
  ["uy", "Uruguay", "Montevideo", "south-america"],
  ["ve", "Venezuela", "Caracas", "south-america"],

  // Asia
  ["af", "Afghanistan", "Kabul", "asia"],
  ["am", "Armenia", "Jerevan", "asia"],
  ["az", "Aserbajdsjan", "Baku", "asia"],
  ["bh", "Bahrain", "Manama", "asia"],
  ["bd", "Bangladesh", "Dhaka", "asia"],
  ["bt", "Bhutan", "Thimphu", "asia"],
  ["bn", "Brunei", "Bandar Seri Begawan", "asia"],
  ["kh", "Kambodsja", "Phnom Penh", "asia"],
  ["cn", "Kina", "Beijing", "asia"],
  ["cy", "Kypros", "Nikosia", "asia"],
  ["ge", "Georgia", "Tbilisi", "asia"],
  ["in", "India", "New Delhi", "asia"],
  ["id", "Indonesia", "Jakarta / Nusantara", "asia"],
  ["ir", "Iran", "Teheran", "asia"],
  ["iq", "Irak", "Bagdad", "asia"],
  ["il", "Israel", "Jerusalem", "asia"],
  ["jp", "Japan", "Tokyo", "asia"],
  ["jo", "Jordan", "Amman", "asia"],
  ["kz", "Kasakhstan", "Astana", "asia"],
  ["kw", "Kuwait", "Kuwait by", "asia"],
  ["kg", "Kirgisistan", "Bisjkek", "asia"],
  ["la", "Laos", "Vientiane", "asia"],
  ["lb", "Libanon", "Beirut", "asia"],
  ["my", "Malaysia", "Kuala Lumpur / Putrajaya", "asia"],
  ["mv", "Maldivene", "Malé", "asia"],
  ["mn", "Mongolia", "Ulaanbaatar", "asia"],
  ["mm", "Myanmar", "Naypyidaw", "asia"],
  ["np", "Nepal", "Katmandu", "asia"],
  ["kp", "Nord-Korea", "Pyongyang", "asia"],
  ["om", "Oman", "Muskat", "asia"],
  ["pk", "Pakistan", "Islamabad", "asia"],
  ["ps", "Palestina", "Øst-Jerusalem / Ramallah", "asia"],
  ["ph", "Filippinene", "Manila", "asia"],
  ["qa", "Qatar", "Doha", "asia"],
  ["sa", "Saudi-Arabia", "Riyadh", "asia"],
  ["sg", "Singapore", "Singapore", "asia"],
  ["kr", "Sør-Korea", "Seoul", "asia"],
  ["lk", "Sri Lanka", "Sri Jayawardenepura Kotte / Colombo", "asia"],
  ["sy", "Syria", "Damaskus", "asia"],
  ["tj", "Tadsjikistan", "Dusjanbe", "asia"],
  ["th", "Thailand", "Bangkok", "asia"],
  ["tl", "Øst-Timor", "Dili", "asia"],
  ["tr", "Tyrkia", "Ankara", "asia"],
  ["tm", "Turkmenistan", "Asjkhabad", "asia"],
  ["ae", "De forente arabiske emirater", "Abu Dhabi", "asia"],
  ["uz", "Usbekistan", "Tasjkent", "asia"],
  ["vn", "Vietnam", "Hanoi", "asia"],
  ["ye", "Jemen", "Sana", "asia"],

  // Europa
  ["al", "Albania", "Tirana", "europe"],
  ["ad", "Andorra", "Andorra la Vella", "europe"],
  ["at", "Østerrike", "Wien", "europe"],
  ["by", "Belarus", "Minsk", "europe"],
  ["be", "Belgia", "Brussel", "europe"],
  ["ba", "Bosnia-Hercegovina", "Sarajevo", "europe"],
  ["bg", "Bulgaria", "Sofia", "europe"],
  ["hr", "Kroatia", "Zagreb", "europe"],
  ["cz", "Tsjekkia", "Praha", "europe"],
  ["dk", "Danmark", "København", "europe"],
  ["ee", "Estland", "Tallinn", "europe"],
  ["fi", "Finland", "Helsinki", "europe"],
  ["fr", "Frankrike", "Paris", "europe"],
  ["de", "Tyskland", "Berlin", "europe"],
  ["gr", "Hellas", "Athen", "europe"],
  ["hu", "Ungarn", "Budapest", "europe"],
  ["is", "Island", "Reykjavík", "europe"],
  ["ie", "Irland", "Dublin", "europe"],
  ["it", "Italia", "Roma", "europe"],
  ["xk", "Kosovo", "Pristina", "europe"],
  ["lv", "Latvia", "Riga", "europe"],
  ["li", "Liechtenstein", "Vaduz", "europe"],
  ["lt", "Litauen", "Vilnius", "europe"],
  ["lu", "Luxembourg", "Luxembourg", "europe"],
  ["mt", "Malta", "Valletta", "europe"],
  ["md", "Moldova", "Chișinău", "europe"],
  ["mc", "Monaco", "Monaco", "europe"],
  ["me", "Montenegro", "Podgorica", "europe"],
  ["nl", "Nederland", "Amsterdam", "europe"],
  ["mk", "Nord-Makedonia", "Skopje", "europe"],
  ["no", "Norge", "Oslo", "europe"],
  ["pl", "Polen", "Warszawa", "europe"],
  ["pt", "Portugal", "Lisboa", "europe"],
  ["ro", "Romania", "București", "europe"],
  ["ru", "Russland", "Moskva", "europe"],
  ["sm", "San Marino", "San Marino", "europe"],
  ["rs", "Serbia", "Beograd", "europe"],
  ["sk", "Slovakia", "Bratislava", "europe"],
  ["si", "Slovenia", "Ljubljana", "europe"],
  ["es", "Spania", "Madrid", "europe"],
  ["se", "Sverige", "Stockholm", "europe"],
  ["ch", "Sveits", "Bern", "europe"],
  ["ua", "Ukraina", "Kyiv", "europe"],
  ["gb", "Storbritannia", "London", "europe"],
  ["va", "Vatikanstaten", "Vatikanstaten", "europe"],

  // Oseania
  ["au", "Australia", "Canberra", "oceania"],
  ["fj", "Fiji", "Suva", "oceania"],
  ["ki", "Kiribati", "South Tarawa", "oceania"],
  ["mh", "Marshalløyene", "Majuro", "oceania"],
  ["fm", "Mikronesiaføderasjonen", "Palikir", "oceania"],
  ["nr", "Nauru", "Yaren", "oceania"],
  ["nz", "New Zealand", "Wellington", "oceania"],
  ["pw", "Palau", "Ngerulmud", "oceania"],
  ["pg", "Papua Ny-Guinea", "Port Moresby", "oceania"],
  ["ws", "Samoa", "Apia", "oceania"],
  ["sb", "Salomonøyene", "Honiara", "oceania"],
  ["to", "Tonga", "Nukuʻalofa", "oceania"],
  ["tv", "Tuvalu", "Funafuti", "oceania"],
  ["vu", "Vanuatu", "Port Vila", "oceania"],
];

const primaryRegions = new Set([
  "europe",
  "africa",
  "asia",
  "oceania",
  "north-central-america",
  "south-america",
  "caribbean",
]);

const countryNotes = Object.freeze({
  cy:
    "FN plasserer Kypros i Vest-Asia i M49-inndelingen, mens landet har vært medlem av EU siden 2004.",
  ru:
    "Russland ligger i både Europa og Asia. I denne quizen er landet plassert i Europa etter FNs M49-inndeling.",
  tr:
    "Tyrkia ligger i både Asia og Europa. I denne quizen er landet plassert i Asia etter FNs M49-inndeling.",
  za:
    "Sør-Afrika har tre hovedsteder: Pretoria er administrativ hovedstad, Cape Town er lovgivende hovedstad, og Bloemfontein er juridisk hovedstad.",
});

const countryCodes = new Set();
const countries = rows.map(([code, name, capital, region]) => {
  if (countryCodes.has(code)) {
    throw new Error(`Duplikat landkode i countries.js: ${code}`);
  }
  if (!primaryRegions.has(region)) {
    throw new Error(`Ugyldig region i countries.js: ${region}`);
  }

  countryCodes.add(code);
  return Object.freeze({
    code,
    name,
    capital,
    region,
    note: countryNotes[code] ?? null,
  });
});

Object.keys(countryNotes).forEach((code) => {
  if (!countryCodes.has(code)) {
    throw new Error(`Landnotat uten tilhørende landkode: ${code}`);
  }
});

const regionOptions = [
  { id: "world", label: "Hele verden" },
  { id: "europe", label: "Europa" },
  { id: "africa", label: "Afrika" },
  { id: "asia", label: "Asia" },
  { id: "oceania", label: "Oseania" },
  { id: "americas", label: "Amerika" },
  {
    id: "north-central-america",
    label: "Nord- og Mellom-Amerika",
  },
  { id: "south-america", label: "Sør-Amerika" },
  { id: "caribbean", label: "Karibia" },
];

window.GEOGRAFI_QUIZ_DATA = Object.freeze({
  countries: Object.freeze(countries),
  regionOptions: Object.freeze(regionOptions),
});
})();
