(function (root, factory) {
  "use strict";

  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.GEOGRAFI_LOCALIZATION = Object.freeze(api);
})(typeof window !== "undefined" ? window : globalThis, function () {
  "use strict";

  const supportedLocales = Object.freeze(["nb", "en"]);

const messages = Object.freeze({
  nb: Object.freeze({
    "pictureCollection": "Bildesamlingen",
    "stagePicture": "Etappebildet",
    "puzzleCount": "{count} / {total} brikker",
    "newPuzzlePiece": "Du fikk en puslespillbrikke!",
    "puzzleContinue": "Fortsett",
    "viewStagePicture": "Se etappebildet",
    "pictureComplete": "Bildet er komplett!",
    "viewPicture": "Se bildet",
    "puzzleZoomControls": "Bildezoom",
    "puzzleZoomIn": "Zoom inn på bildet",
    "puzzleZoomOut": "Zoom ut fra bildet",
    "puzzleZoomReset": "Tilbakestill bildezoom",
    "puzzleHelp": "Bruk zoomknappene, knip med to fingre eller bruk Ctrl og rullehjulet for å zoome. Dra eller bruk piltastene for å flytte bildet. Tilbakestill zoom for å se hele bildet.",
    "puzzleInspect": "Utforsk puslespillet. Bruk piltastene for å rulle når du har zoomet inn.",
    "puzzleImageUnavailable": "Bildet kunne ikke lastes. Brikkene dine er fortsatt registrert.",
    "puzzleDescription_tourist": "En travel togstasjon med reisende, rampete dyr og kofferter fulle av overraskelser.",
    "puzzleDescription_explorer": "En eventyrøy med trehytter, grotter, nysgjerrige dyr og oppdagere på tur.",
    "puzzleDescription_navigator": "En livlig havn og en undervannsverden med båter, sjøskapninger og små eventyr.",
    "puzzleDescription_globetrotter": "En fantasiby med tog, luftballonger, taubaner og reisende på kryss og tvers.",
    "puzzleDescription_regional-expert": "Et kartmakerverksted der små fjell, elver, byer og dyr våkner til liv.",
    "puzzleDescription_world-master": "En liten eventyrplanet der reisende og dyr fra hele reisen møtes til fest.",

    modeCountryFlagShort: "Finn flagget",
    modeFlagCountryShort: "Finn riktig navn",
    modeCountryCapitalShort: "Finn hovedstaden",
    modeMapCountryShort: "Les kartet",
    brandName: "Hei verden!",
    flagOf: "Flagget til {name}",
    homeLink: "Tilbake til lanceolav.com",
    brandTop: "Hei verden! – til toppen",
    brandHome: "Hei verden! – gå til forsiden",
    home: "Forsiden",
    languageGroup: "Velg språk",
    languageNb: "Norsk",
    languageEn: "English",
    countries: "{count} land",
    otherPlaces: "{count} andre steder",
    places: "{count} steder",
    placeBreakdown: "{countries} land · {otherPlaces} andre steder",
    countriesHeading: "Land",
    otherPlacesHeading: "Andre steder",
    otherCompactHeading: "Andre",
    establishedLocalFlag: "Etablert lokalt flagg",
    regionMapDescription:
      "Velg et område på kartet, eller bruk områdeknappene ved siden av.",
    interactiveWorldMap: "Interaktivt verdenskart",
    shrinkShape: "Vis kartfiguren mindre",
    enlargeShape: "Vis kartfiguren større",
    changeRegion: "Bytt region",
    exploreOnMap: "Utforsk {name} på kartet",
    backToResults: "Tilbake til resultatet",
    resultsDestination: "Resultatet",
    backToLevels: "Tilbake til nivåene",
    highlightedMap: "Kart over {region} med ett sted uthevet",
    highlightedWorldMap: "Verdenskart med ett sted uthevet",
    highlightedNearbyMap:
      "Kartutsnitt av nærområdet i {region} med ett sted uthevet",
    mapViewWorld: "Verden",
    mapViewRegion: "Region",
    mapViewNearby: "Nærområde",
    heroKicker: "Lek. Lær. Utforsk.",
    heroTitleBefore: "Verden",
    heroTitleEmphasis: "venter.",
    chooseActivity: "Velg aktivitet",
    testYourself: "Test deg selv",
    explore: "Utforsk",
    flagsLicence: "Flagg fra flag-icons · MIT",
    localFlagsLicence: "Lokale flagg · kildeinfo",
    globeLicence: "Jordklode fra Twemoji · CC BY 4.0",
    mapLicence: "Kart fra Natural Earth · public domain",
    installApp: "Legg til på Hjem-skjermen",
    installHelpTitle: "Legg til på Hjem-skjermen",
    installHelpText:
      "Trykk på Del i nettleseren, velg «Legg til på Hjem-skjermen», slå på «Åpne som webapp», og trykk «Legg til».",
    installSafariTitle: "Åpne i Safari",
    installSafariText:
      "Åpne denne siden i Safari for å legge den til på Hjem-skjermen. Trykk deretter på Del, velg «Legg til på Hjem-skjermen», slå på «Åpne som webapp», og trykk «Legg til».",
    closeInstallHelp: "Lukk",
    review: "Gjennomgang",
    reviewHeading: "{count} {count, plural, one {sted} other {steder}} å øve på",
    questionsLabel: "Spørsmål",
    startChallenge: "Start utfordringen",
    unverifiedScore:
      "Poengsummen i lenken kunne ikke bekreftes. Du kan fortsatt spille den samme runden.",
    invalidChallengeKicker: "Ugyldig utfordring",
    invalidChallengeTitle: "Denne utfordringslenken virker ikke.",
    invalidChallengeDescription:
      "Lenken mangler en gyldig quiz-ID, versjon eller revisjon.",
    challengeBeat: "Du slo resultatet på {target} poeng!",
    challengeTied: "Du matchet resultatet: {target} poeng.",
    challengePerfectTied:
      "Perfekt! Du matchet utfordringen med full poengsum.",
    challengeMissed:
      "Du fikk {score} poeng; resultatet å matche var {target}.",
    challengeShareFailed: "Kunne ikke dele utfordringen.",
    close: "Lukk",
    openSharedLink: "Åpne delt lenke",
    openSharedLinkPrompt: "Har du fått en lenke?",
    openSharedLinkDescription:
      "Lim inn en utfordring, profiloverføring eller invitasjon. Du kan også lime inn hele den delte meldingen.",
    sharedLinkInputLabel: "Delt lenke eller melding",
    sharedLinkInputPlaceholder: "https://… eller en delt melding",
    cancel: "Avbryt",
    sharedLinkRequired: "Lim inn en delt lenke eller melding.",
    sharedLinkMalformed: "Fant ikke én gyldig nettadresse.",
    sharedLinkWrongApp: "Lenken tilhører ikke denne geografiappen.",
    sharedLinkInvalidChallenge: "Dette er ikke en gyldig utfordringslenke.",
    sharedLinkInvalidTransfer: "Dette er ikke en gyldig overføringslenke.",
    sharedLinkUnsupported: "Denne typen lenke kan ikke åpnes her.",
    chooseCountry: "Velg et sted",
    backToExplore: "Tilbake til Utforsk",
    flashcards: "Øvingskort",
    exploreTheseCountries: "Utforsk disse stedene",
    missedCountries: "Steder å øve på",
    wholeWorld: "Hele verden",
    countryCapital: "{name}, hovedstad {capital}",
    interactiveRegionMap: "Interaktivt kart over {region}",
    countriesInRegion: "Steder i regionen",
    mapZoomControls: "Kartzoom",
    zoomOutMap: "Zoom ut på kartet",
    zoomInMap: "Zoom inn på kartet",
    resetMapZoom: "Tilbakestill kartzoom, {percent} prosent",
    showRegion: "Vis region",
    viewWorld: "Vis verden",
    mapAreaControls: "Bytt kartutsnitt",
    exploreMapHeading: "Hvilket kart vil du utforske?",
    chooseSingleRegion: "Velg en enkelt region",
    showCountryDetails: "Vis detaljer for {name}",
    countryDetails: "Stedsdetaljer: {name}",
    flashcardsComplete: "Øvingskort",
    roundComplete: "Runden er fullført",
    flashcardsSummaryBefore: "Du har gått gjennom",
    flashcardsSummaryAfter: "flagg fra",
    revealedFlashcard:
      "{name}, {capital}. Velg for å gå til neste flagg.",
    revealedRelatedFlashcard:
      "{name}, {capital} ({relationship}). Velg for å gå til neste flagg.",
    hiddenFlashcard:
      "Øvingskort {current} av {total}. Velg for å vise svaret.",
    findFlag: "Finn flagget til",
    whichCountry: "Hvilket sted?",
    findCapital: "Finn hovedstaden til",
    option: "Alternativ {number}",
    flagOption: "Flaggalternativ {number}",
    correctContinue:
      "{label}, riktig svar. Velg for å gå videre.",
    correctAnswer: "{label}, riktig svar",
    correctAnnouncement: "Riktig.",
    wrongAnnouncement:
      "Feil. Riktig svar er {answer}. Aktiver det markerte alternativet for å gå videre.",
    metaTitle: "Hei verden! – lær land, flagg, hovedsteder og kart",
    metaDescription:
      "Utforsk og test deg selv på 197 land og 30 andre steder, med flagg, hovedsteder og regionale kart.",
  }),
  en: Object.freeze({
    "pictureCollection": "Picture collection",
    "stagePicture": "Stage picture",
    "puzzleCount": "{count} / {total} pieces",
    "newPuzzlePiece": "You earned a puzzle piece!",
    "puzzleContinue": "Continue",
    "viewStagePicture": "View stage picture",
    "pictureComplete": "Picture complete!",
    "viewPicture": "View picture",
    "puzzleZoomControls": "Picture zoom",
    "puzzleZoomIn": "Zoom in on picture",
    "puzzleZoomOut": "Zoom out of picture",
    "puzzleZoomReset": "Reset picture zoom",
    "puzzleHelp": "Use the zoom buttons, pinch with two fingers, or use Ctrl and the mouse wheel to zoom. Drag or use arrow keys to pan. Reset zoom to see the whole picture.",
    "puzzleInspect": "Inspect the puzzle. Use arrow keys to scroll when zoomed in.",
    "puzzleImageUnavailable": "The picture could not load. Your earned pieces are still recorded.",
    "puzzleDescription_tourist": "A bustling railway station with travellers, mischievous animals, and suitcases full of surprises.",
    "puzzleDescription_explorer": "An adventure island with treehouses, caves, curious animals, and explorers on an expedition.",
    "puzzleDescription_navigator": "A lively harbour and underwater world with boats, sea creatures, and little adventures.",
    "puzzleDescription_globetrotter": "A fantasy city with trains, balloons, cable cars, and travellers crossing paths.",
    "puzzleDescription_regional-expert": "A mapmaker’s workshop where miniature mountains, rivers, towns, and animals come alive.",
    "puzzleDescription_world-master": "A little adventure planet where travellers and animals from the whole journey gather to celebrate.",

    modeCountryFlagShort: "Find the flag",
    modeFlagCountryShort: "Match the name",
    modeCountryCapitalShort: "Find the capital",
    modeMapCountryShort: "Read the map",
    brandName: "Hello World!",
    flagOf: "Flag of {name}",
    homeLink: "Back to lanceolav.com",
    brandTop: "Hello World! – back to top",
    brandHome: "Hello World! – go to the home page",
    home: "Home",
    languageGroup: "Choose language",
    languageNb: "Norsk",
    languageEn: "English",
    countries: "{count} {count, plural, one {country} other {countries}}",
    otherPlaces: "{count} {count, plural, one {other place} other {other places}}",
    places: "{count} places",
    placeBreakdown: "{countries} countries · {otherPlaces} other places",
    countriesHeading: "Countries",
    otherPlacesHeading: "Other places",
    otherCompactHeading: "Other",
    establishedLocalFlag: "Established local flag",
    regionMapDescription:
      "Choose an area on the map, or use the area buttons beside it.",
    interactiveWorldMap: "Interactive world map",
    shrinkShape: "Show a smaller map shape",
    enlargeShape: "Show a larger map shape",
    changeRegion: "Change region",
    exploreOnMap: "Explore {name} on the map",
    backToResults: "Back to results",
    resultsDestination: "Results",
    backToLevels: "Back to levels",
    highlightedMap: "Map of {region} with one place highlighted",
    highlightedWorldMap: "World map with one place highlighted",
    highlightedNearbyMap:
      "Nearby view of {region} with one place highlighted",
    mapViewWorld: "World",
    mapViewRegion: "Region",
    mapViewNearby: "Nearby",
    heroKicker: "Play. Learn. Explore.",
    heroTitleBefore: "The world",
    heroTitleEmphasis: "awaits.",
    chooseActivity: "Choose activity",
    testYourself: "Test yourself",
    explore: "Explore",
    flagsLicence: "Flags from flag-icons · MIT",
    localFlagsLicence: "Local flags · source details",
    globeLicence: "Globe from Twemoji · CC BY 4.0",
    mapLicence: "Maps from Natural Earth · public domain",
    installApp: "Add to Home Screen",
    installHelpTitle: "Add to Home Screen",
    installHelpText:
      "Tap Share in the browser, choose “Add to Home Screen”, turn on “Open as Web App”, and tap “Add”.",
    installSafariTitle: "Open in Safari",
    installSafariText:
      "Open this page in Safari to add it to your Home Screen. Then tap Share, choose “Add to Home Screen”, turn on “Open as Web App”, and tap “Add”.",
    closeInstallHelp: "Close",
    review: "Review",
    reviewHeading:
      "{count} {count, plural, one {place} other {places}} to review",
    questionsLabel: "Questions",
    startChallenge: "Start challenge",
    unverifiedScore:
      "The score in this link could not be verified. You can still play the same round.",
    invalidChallengeKicker: "Invalid challenge",
    invalidChallengeTitle: "This challenge link does not work.",
    invalidChallengeDescription:
      "The link is missing a valid quiz ID, version, or revision.",
    challengeBeat: "You beat the score of {target}!",
    challengeTied: "You matched the score: {target}.",
    challengePerfectTied:
      "Perfect! You matched the challenge with a full score.",
    challengeMissed: "You scored {score}; the score to match was {target}.",
    challengeShareFailed: "Could not share the challenge.",
    close: "Close",
    openSharedLink: "Open shared link",
    openSharedLinkPrompt: "Have you received a link?",
    openSharedLinkDescription:
      "Paste a challenge, profile transfer, or invitation. You can also paste the complete shared message.",
    sharedLinkInputLabel: "Shared link or message",
    sharedLinkInputPlaceholder: "https://… or a shared message",
    cancel: "Cancel",
    sharedLinkRequired: "Paste a shared link or message.",
    sharedLinkMalformed: "Could not find one valid web address.",
    sharedLinkWrongApp: "This link does not belong to this geography app.",
    sharedLinkInvalidChallenge: "This is not a valid challenge link.",
    sharedLinkInvalidTransfer: "This is not a valid transfer link.",
    sharedLinkUnsupported: "This type of link cannot be opened here.",
    chooseCountry: "Choose a place",
    backToExplore: "Back to Explore",
    flashcards: "Flashcards",
    exploreTheseCountries: "Explore these places",
    missedCountries: "Places to revisit",
    wholeWorld: "Whole world",
    countryCapital: "{name}, capital {capital}",
    interactiveRegionMap: "Interactive map of {region}",
    countriesInRegion: "Places in the region",
    mapZoomControls: "Map zoom",
    zoomOutMap: "Zoom out of the map",
    zoomInMap: "Zoom into the map",
    resetMapZoom: "Reset map zoom, {percent} per cent",
    showRegion: "Show region",
    viewWorld: "View world",
    mapAreaControls: "Change map area",
    exploreMapHeading: "Which map would you like to explore?",
    chooseSingleRegion: "Choose a single region",
    showCountryDetails: "Show details for {name}",
    countryDetails: "Place details: {name}",
    flashcardsComplete: "Flashcards",
    roundComplete: "Round complete",
    flashcardsSummaryBefore: "You have reviewed",
    flashcardsSummaryAfter: "flags from",
    revealedFlashcard:
      "{name}, {capital}. Choose to continue to the next flag.",
    revealedRelatedFlashcard:
      "{name}, {capital} ({relationship}). Choose to continue to the next flag.",
    hiddenFlashcard:
      "Flashcard {current} of {total}. Choose to reveal the answer.",
    findFlag: "Find the flag of",
    whichCountry: "Which place?",
    findCapital: "Find the capital of",
    option: "Option {number}",
    flagOption: "Flag option {number}",
    correctContinue:
      "{label}, correct answer. Choose to continue.",
    correctAnswer: "{label}, correct answer",
    correctAnnouncement: "Correct.",
    wrongAnnouncement:
      "Incorrect. The correct answer is {answer}. Activate the highlighted option to continue.",
    metaTitle: "Hello World! – learn countries, flags, capitals and maps",
    metaDescription:
      "Explore and test yourself on 197 countries and 30 other places, with flags, capitals and regional maps.",
  }),
});
const progressionMessages = Object.freeze({
  nb: Object.freeze({
    startGame: "Start spillet", continueGame: "Fortsett spillet", exploreWorld: "Utforsk verden",
    viewLevels: "Se alle nivåer", levels: "Nivåer", level: "Nivå {number}",
    levelRange: "Nivå {start}–{end}",
    levelsMastered: "{count} av {total} nivåer mestret", quizzesMastered: "{count} av 4 quizer mestret",
    mastered: "mestret", unplayed: "Ikke spilt", recommended: "Anbefalt neste",
    profileMenu: "Profil og innstillinger", addProfile: "Legg til profil", renameProfile: "Gi profilen nytt navn",
    switchProfile: "Bytt profil", clearProgress: "Nullstill fremgang", deleteProfile: "Slett profil",
    newProfileName: "Navn på ny profil", settings: "Innstillinger",
    transferProfile: "Overfør denne profilen", copyTransferLink: "Kopier overføringslenke",
    transferCopied: "Overføringslenken er kopiert.", transferFailed: "Kunne ikke kopiere lenken.",
    backupHeading: "Sikkerhetskopi", downloadBackup: "Last ned sikkerhetskopi",
    importBackup: "Importer sikkerhetskopi", importProgress: "Importer fremgang",
    createProfile: "Opprett profil", updateProfile: "Oppdater {name}", mergeProfile: "Slå sammen", mergeInto: "Slå sammen med {name}",
    importAll: "Importer alle profiler", importOne: "Importer", importCancel: "Avbryt",
    playedAndMastered: "{played} quizer spilt · {mastered} mestret", invalidImport: "Lenken eller sikkerhetskopien er ugyldig.",
    storageReadFailed: "Lagret fremgang kunne ikke leses. Du kan fortsatt utforske og spille.",
    storageWriteFailed: "Fremgangen kunne ikke lagres på denne enheten.",
    quizMastered: "Quiz mestret", levelMasteredResult: "Nivå mestret", quizNotMastered: "Ikke helt ennå", scoreOutOf: "av {total}",
    scoreAnnouncement: "{score} av {total}", newRecord: "Ny rekord!", recordScore: "Rekord: {score} av {total}",
    nextQuiz: "Neste quiz", nextResultMode: "Neste: {mode}", nextQuizDestination: "{action}: Nivå {number} · {title} · {mode}", nextLevelAction: "Neste", congratulations: "Gratulerer!", tryAgainAction: "Prøv igjen", playAgain: "Spill igjen",
    levelQuizProgress: "Fremgang på nivået", resultModeMastered: "{mode}, mestret. Spill igjen.",
    resultModePlayed: "{mode}, rekord {score} av {total}. Spill quizen.", resultModeUnplayed: "{mode}, ikke spilt. Start quizen.",
    milestones: "Milepæler", milestoneReached: "Milepæl nådd", milestoneSummary: "Du har mestret nivå {start}–{end}.",
    milestoneAction: "Fullført:", openMilestoneCelebration: "Åpne feiringen for {stage}", replayMilestone: "Spill feiringen for {stage} igjen",
    replayWorldCelebration: "Spill «Verden mestret»-feiringen igjen",
    milestoneLocked: "{stage} er ikke oppnådd ennå", nextStage: "Neste etappe: {stage}", continueWithStage: "Fortsett med: {stage}",
    worldMasteredAction: "Verden mestret", stageMastered: "Mestret",
    worldCelebrationSummary: "Du har mestret alle {levels} nivåene og alle {quizzes} quizene.",
    reviewCards: "Øv med øvingskort", retryQuiz: "Prøv quizen igjen", backToLevel: "Tilbake til nivået",
    worldMastered: "Verden mestret", surpriseQuiz: "Overraskelsesquiz", chooseLevel: "Velg nivå",
    shareProgress: "Del fremgangen min", challengeThisQuiz: "Utfordre en venn",
    milestoneShareSubject: "Jeg nådde {stage} i Hei verden!",
    milestoneShareText: "Jeg har nådd {stage} og mestret nivå {start}–{end} i Hei verden!",
    milestoneShareSubjectNamed: "{name} nådde {stage} i Hei verden!",
    milestoneShareTextNamed: "{name} har nådd milepælen {stage} og mestret nivå {start}–{end} i Hei verden!",
    worldShareSubject: "Jeg har mestret verden i Hei verden!",
    worldShareText: "Jeg har mestret alle {levels} nivåene og alle {quizzes} geografiquizene i Hei verden!",
    worldShareSubjectNamed: "{name} har mestret verden i Hei verden!",
    worldShareTextNamed: "{name} har mestret alle {levels} nivåene og alle {quizzes} geografiquizene i Hei verden!",
    challengeShareSubject: "Geografiutfordring i Hei verden!",
    challengeShareSubjectNamed: "Utfordring i Hei verden! fra {name}",
    challengeShareText: "Jeg fikk {score} av {total} i nivå {level}: {levelTitle} · {mode}. Klarer du å slå resultatet mitt? Quizen tar omtrent {minutes} min.",
    challengeShareTextNamed: "{name} fikk {score} av {total} i nivå {level}: {levelTitle} · {mode}. Klarer du å slå resultatet? Quizen tar omtrent {minutes} min.",
    challengeEmailCallToAction: "Åpne utfordringen:",
    progressEmailCallToAction: "Utforsk Hei verden!:",
    openEmailDraft: "Åpne e-postutkast",
    copyMessage: "Kopier melding",
    shareMessageCopied: "Meldingen er kopiert.",
    goToRecommended: "Gå til anbefalt neste quiz",
    cards: "Øv med øvingskort", questionsLong: "{count} spørsmål · lang quiz",
    quizInProgress: "Quiz pågår", continueMode: "Fortsett: {mode}",
    answeredProgress: "{answered} / {total} besvart", keepSavedAttempt: "Tilbake",
    abandonAttemptTitle: "Starte en annen quiz?",
    abandonAttemptDescription: "Den påbegynte mestringsquizen blir avbrutt.",
    abandonAndStart: "Start quiz",
    addProfileTitle: "Legg til profil", addProfileDescription: "Fremgangen til den nye profilen lagres separat på denne enheten.",
    addProfileAction: "Opprett profil", renameProfileTitle: "Gi profilen nytt navn",
    renameProfileDescription: "Skriv inn et nytt navn for {name}.", renameProfileAction: "Lagre navn",
    clearProgressTitle: "Vil du nullstille fremgangen?", clearProgressDescription: "Alle quizresultater og eventuelle lagrede forsøk for {name} slettes. Profilen beholdes.",
    clearProgressAction: "Nullstill fremgang", deleteProfileTitle: "Vil du slette profilen?",
    deleteProfileDescription: "Profilen {name} og all fremgangen dens slettes fra denne enheten. Dette kan ikke angres.",
    deleteProfileAction: "Slett profil",
    updatedQuizzes: "Noen quizer er oppdatert og klare til å spilles igjen.",
    challengeQuizTitle: "Quizutfordring", scoreToBeat: "Resultat å slå", approximateTime: "Omtrent {minutes} min",
    shareUnavailable: "Kunne ikke dele akkurat nå.", profilePrivacy: "Fremgangen lagres bare på denne enheten.",
  }),
  en: Object.freeze({
    startGame: "Start game", continueGame: "Continue game", exploreWorld: "Explore the world",
    viewLevels: "View all levels", levels: "Levels", level: "Level {number}",
    levelRange: "Levels {start}–{end}",
    levelsMastered: "{count} of {total} levels mastered", quizzesMastered: "{count} of 4 quizzes mastered",
    mastered: "mastered", unplayed: "Unplayed", recommended: "Recommended next",
    profileMenu: "Profile and settings", addProfile: "Add profile", renameProfile: "Rename profile",
    switchProfile: "Switch profile", clearProgress: "Clear progress", deleteProfile: "Delete profile",
    newProfileName: "New profile name", settings: "Settings",
    transferProfile: "Transfer this profile", copyTransferLink: "Copy transfer link",
    transferCopied: "Transfer link copied.", transferFailed: "Could not copy the link.",
    backupHeading: "Backup", downloadBackup: "Download backup file",
    importBackup: "Import backup file", importProgress: "Import progress",
    createProfile: "Create profile", updateProfile: "Update {name}", mergeProfile: "Merge", mergeInto: "Merge with {name}",
    importAll: "Import all profiles", importOne: "Import", importCancel: "Cancel",
    playedAndMastered: "{played} quizzes played · {mastered} mastered", invalidImport: "This link or backup file is invalid.",
    storageReadFailed: "Saved progress could not be read. You can still explore and play.",
    storageWriteFailed: "Progress could not be saved on this device.",
    quizMastered: "Quiz mastered", levelMasteredResult: "Level mastered", quizNotMastered: "Not quite yet", scoreOutOf: "of {total}",
    scoreAnnouncement: "{score} of {total}", newRecord: "New record!", recordScore: "Record: {score} of {total}",
    nextQuiz: "Next quiz", nextResultMode: "Next: {mode}", nextQuizDestination: "{action}: Level {number} · {title} · {mode}", nextLevelAction: "Next", congratulations: "Congratulations!", tryAgainAction: "Try again", playAgain: "Play again",
    levelQuizProgress: "Level progress", resultModeMastered: "{mode}, mastered. Play again.",
    resultModePlayed: "{mode}, best score {score} of {total}. Play quiz.", resultModeUnplayed: "{mode}, unplayed. Start quiz.",
    milestones: "Milestones", milestoneReached: "Milestone reached", milestoneSummary: "You mastered levels {start}–{end}.",
    milestoneAction: "Completed:", openMilestoneCelebration: "Open the {stage} celebration", replayMilestone: "Replay the {stage} celebration",
    replayWorldCelebration: "Replay the world mastery celebration",
    milestoneLocked: "{stage} has not been earned yet", nextStage: "Next stage: {stage}", continueWithStage: "Continue with: {stage}",
    worldMasteredAction: "World mastered", stageMastered: "Mastered",
    worldCelebrationSummary: "You have mastered all {levels} levels and all {quizzes} quizzes.",
    reviewCards: "Review with flashcards", retryQuiz: "Retry quiz", backToLevel: "Back to level",
    worldMastered: "World mastered", surpriseQuiz: "Surprise quiz", chooseLevel: "Choose a level",
    shareProgress: "Share my progress", challengeThisQuiz: "Challenge a friend",
    milestoneShareSubject: "I reached {stage} in Hello World!",
    milestoneShareText: "I reached {stage} and mastered levels {start}–{end} in Hello World!",
    milestoneShareSubjectNamed: "{name} reached {stage} in Hello World!",
    milestoneShareTextNamed: "{name} reached the {stage} milestone and mastered levels {start}–{end} in Hello World!",
    worldShareSubject: "I mastered the world in Hello World!",
    worldShareText: "I mastered all {levels} levels and all {quizzes} geography quizzes in Hello World!",
    worldShareSubjectNamed: "{name} mastered the world in Hello World!",
    worldShareTextNamed: "{name} mastered all {levels} levels and all {quizzes} geography quizzes in Hello World!",
    challengeShareSubject: "Hello World! geography challenge",
    challengeShareSubjectNamed: "Hello World! challenge from {name}",
    challengeShareText: "I scored {score}/{total} in Level {level}: {levelTitle} · {mode}. Can you beat my score? About {minutes} min.",
    challengeShareTextNamed: "{name} scored {score}/{total} in Level {level}: {levelTitle} · {mode}. Can you beat the score? About {minutes} min.",
    challengeEmailCallToAction: "Open the challenge:",
    progressEmailCallToAction: "Explore Hello World!:",
    openEmailDraft: "Open email draft",
    copyMessage: "Copy message",
    shareMessageCopied: "Message copied.",
    goToRecommended: "Go to the recommended next quiz",
    cards: "Practice with flashcards", questionsLong: "{count} questions · long quiz",
    quizInProgress: "Quiz in progress", continueMode: "Continue: {mode}",
    answeredProgress: "{answered} / {total} answered", keepSavedAttempt: "Go back",
    abandonAttemptTitle: "Start another quiz?",
    abandonAttemptDescription: "Your unfinished mastery quiz will be cancelled.",
    abandonAndStart: "Start quiz",
    addProfileTitle: "Add profile", addProfileDescription: "The new profile’s progress will be stored separately on this device.",
    addProfileAction: "Create profile", renameProfileTitle: "Rename profile",
    renameProfileDescription: "Enter a new name for {name}.", renameProfileAction: "Save name",
    clearProgressTitle: "Clear progress?", clearProgressDescription: "All quiz results and any saved attempt for {name} will be deleted. The profile will remain.",
    clearProgressAction: "Clear progress", deleteProfileTitle: "Delete profile?",
    deleteProfileDescription: "The profile {name} and all of its progress will be deleted from this device. This cannot be undone.",
    deleteProfileAction: "Delete profile",
    updatedQuizzes: "Some quizzes were updated and are ready to play again.",
    challengeQuizTitle: "Quiz challenge", scoreToBeat: "Score to beat", approximateTime: "About {minutes} min",
    shareUnavailable: "Could not share right now.", profilePrivacy: "Progress is stored only on this device.",
  }),
});

  function validateCatalog(catalog, name) {
    const referenceKeys = Object.keys(catalog.nb);
    supportedLocales.forEach((locale) => {
      if (Object.keys(catalog[locale]).length !== referenceKeys.length) {
        throw new Error(`Unexpected ${locale} ${name} translation key`);
      }
      referenceKeys.forEach((key) => {
        if (!catalog[locale][key]) {
          throw new Error(`Missing ${locale} translation: ${key}`);
        }
      });
    });
  }

  validateCatalog(messages, "interface");
  validateCatalog(progressionMessages, "progression");

  function translate(locale, key, values = {}) {
    if (!supportedLocales.includes(locale)) {
      throw new Error(`Unsupported locale: ${locale}`);
    }

    let value = messages[locale][key] ?? progressionMessages[locale][key];
    if (!value) throw new Error(`Missing ${locale} translation: ${key}`);

    value = value.replace(
      /\{(\w+), plural, one \{([^{}]+)\} other \{([^{}]+)\}\}/g,
      (_match, variable, singular, plural) =>
        Number(values[variable]) === 1 ? singular : plural,
    );
    return value.replace(/\{(\w+)\}/g, (_match, variable) =>
      String(values[variable] ?? ""),
    );
  }

  return Object.freeze({ supportedLocales, translate });
});
